package com.influencermatch.backend.common;

import jakarta.persistence.Column;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.SuperBuilder;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Abstract superclass for all JPA entities in the InfluencerMatch platform.
 *
 * <p>Provides:
 * <ul>
 *   <li>A UUID v4 primary key (auto-generated by the JVM, not the DB sequence).</li>
 *   <li>Immutable {@code createdAt} timestamp populated by Spring Data Auditing.</li>
 *   <li>Auto-updated {@code updatedAt} timestamp populated by Spring Data Auditing.</li>
 * </ul>
 *
 * <p>All concrete entity classes must extend this class and be annotated with
 * {@link jakarta.persistence.Entity} and {@link jakarta.persistence.Table}.
 */
@Getter
@Setter
@NoArgsConstructor
@SuperBuilder
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public abstract class BaseEntity {

    /**
     * Universally unique identifier for this entity.
     * Generated client-side (JVM) using UUID v4 strategy to avoid DB round-trips
     * and to remain portable across database migrations.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(updatable = false, nullable = false)
    private UUID id;

    /**
     * Timestamp of entity creation, set once by the auditing framework.
     * Marked {@code updatable = false} to prevent accidental mutations.
     */
    @CreatedDate
    @Column(updatable = false, nullable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp of the last entity update, maintained automatically by
     * the auditing framework on every {@code persist} and {@code merge} operation.
     */
    @LastModifiedDate
    @Column(nullable = false)
    private LocalDateTime updatedAt;
}


